### ISSUE TITLE
You're currently using both PData & maestro's storage system

### ISSUE THREAD

**Issue by bmwalters** [DaaOtt/maestro-tempo#1]
Needs to be changed to not use PData anymore, should just need to replace ply:SetPData(k, v) -> ply.k = v and ply:GetPData(k) to ply.k

**Comment by ottworks** [comment]
no

**Comment by ottworks** [comment]
it's ~backwards compatible~

**Comment by bmwalters** [comment]
> implying people who don't update use maestro

i would argue that maestro is such a new tool that it is fine to remove old functionality to avoid code bloat
